#############################################################################
# Generated by PAGE version 4.13
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_4_0 .top37.tNo38.t0 
    set site_4_0 $site_4_0
    set site_4_1 .top37.tNo38.t1 
    set site_4_0 $site_4_1
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 305x350+658+296
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3825 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "npSettings" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo38 \
        -width 302 -height 306 -takefocus {} 
    vTcl:DefineAlias "$top.tNo38" "TNotebook1" vTcl:WidgetProc "npSettings" 1
    frame $top.tNo38.t0 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo38.t0" "TNotebook1_t0" vTcl:WidgetProc "npSettings" 1
    $top.tNo38 add $top.tNo38.t0 \
        -padding 0 -sticky nsew -state normal -text {IP & COM settings} \
        -image {} -compound left -underline -1 
    set site_4_0  $top.tNo38.t0
    ttk::label $site_4_0.tLa44 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {IP1 address} 
    vTcl:DefineAlias "$site_4_0.tLa44" "TLabel1" vTcl:WidgetProc "npSettings" 1
    ttk::entry $site_4_0.tEn45 \
        -textvariable ip1 -foreground {} -background {} -takefocus {} \
        -cursor xterm 
    vTcl:DefineAlias "$site_4_0.tEn45" "IP1Edit" vTcl:WidgetProc "npSettings" 1
    ttk::label $site_4_0.tLa46 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {IP2 address} 
    vTcl:DefineAlias "$site_4_0.tLa46" "TLabel2" vTcl:WidgetProc "npSettings" 1
    ttk::entry $site_4_0.tEn47 \
        -textvariable ip2 -foreground {} -background {} -takefocus {} \
        -cursor xterm 
    vTcl:DefineAlias "$site_4_0.tEn47" "IP2Edit" vTcl:WidgetProc "npSettings" 1
    ttk::label $site_4_0.tLa48 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {Reboot modem on unavialibility of} 
    vTcl:DefineAlias "$site_4_0.tLa48" "TLabel3" vTcl:WidgetProc "npSettings" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_4_0.tCh49 \
        -variable ip1rebootChecked -takefocus {} -text IP1 
    vTcl:DefineAlias "$site_4_0.tCh49" "ip1reboot" vTcl:WidgetProc "npSettings" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_4_0.tCh50 \
        -variable ip2rebootChecked -takefocus {} -text IP2 
    vTcl:DefineAlias "$site_4_0.tCh50" "ip2reboot" vTcl:WidgetProc "npSettings" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_4_0.tCh51 \
        -variable comPortEnabledChecked -takefocus {} -text {Enable COM-port} 
    vTcl:DefineAlias "$site_4_0.tCh51" "comPortEnabled" vTcl:WidgetProc "npSettings" 1
    ttk::entry $site_4_0.tEn52 \
        -textvariable comPort -foreground {} -background {} -takefocus {} \
        -cursor xterm 
    vTcl:DefineAlias "$site_4_0.tEn52" "comEdit" vTcl:WidgetProc "npSettings" 1
    ttk::label $site_4_0.tLa53 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text COM-speed 
    vTcl:DefineAlias "$site_4_0.tLa53" "TLabel4" vTcl:WidgetProc "npSettings" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_4_0.tCh54 \
        -variable enableAutoSpeed -takefocus {} -text auto 
    vTcl:DefineAlias "$site_4_0.tCh54" "enableAutoSpeedCheckbox" vTcl:WidgetProc "npSettings" 1
    ttk::entry $site_4_0.tEn55 \
        -textvariable comSpeed -foreground {} -background {} -takefocus {} \
        -cursor xterm 
    vTcl:DefineAlias "$site_4_0.tEn55" "TEntry4" vTcl:WidgetProc "npSettings" 1
    ttk::entry $site_4_0.tEn56 \
        -textvariable critTemp -foreground {} -background {} -takefocus {} \
        -cursor xterm 
    vTcl:DefineAlias "$site_4_0.tEn56" "TEntry5" vTcl:WidgetProc "npSettings" 1
    ttk::label $site_4_0.tLa57 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {Critical temperature} 
    vTcl:DefineAlias "$site_4_0.tLa57" "TLabel5" vTcl:WidgetProc "npSettings" 1
    place $site_4_0.tLa44 \
        -in $site_4_0 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_4_0.tEn45 \
        -in $site_4_0 -x 110 -y 10 -width 164 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa46 \
        -in $site_4_0 -x 10 -y 40 -anchor nw -bordermode ignore 
    place $site_4_0.tEn47 \
        -in $site_4_0 -x 110 -y 40 -width 164 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa48 \
        -in $site_4_0 -x 10 -y 70 -anchor nw -bordermode ignore 
    place $site_4_0.tCh49 \
        -in $site_4_0 -x 210 -y 70 -anchor nw -bordermode ignore 
    place $site_4_0.tCh50 \
        -in $site_4_0 -x 260 -y 70 -anchor nw -bordermode ignore 
    place $site_4_0.tCh51 \
        -in $site_4_0 -x 10 -y 110 -anchor nw -bordermode ignore 
    place $site_4_0.tEn52 \
        -in $site_4_0 -x 130 -y 110 -width 144 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa53 \
        -in $site_4_0 -x 10 -y 140 -anchor nw -bordermode ignore 
    place $site_4_0.tCh54 \
        -in $site_4_0 -x 80 -y 140 -anchor nw -bordermode ignore 
    place $site_4_0.tEn55 \
        -in $site_4_0 -x 130 -y 140 -anchor nw -bordermode ignore 
    place $site_4_0.tEn56 \
        -in $site_4_0 -x 130 -y 170 -anchor nw -bordermode ignore 
    place $site_4_0.tLa57 \
        -in $site_4_0 -x 10 -y 170 -anchor nw -bordermode ignore 
    frame $top.tNo38.t1 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo38.t1" "TNotebook1_t1" vTcl:WidgetProc "npSettings" 1
    $top.tNo38 add $top.tNo38.t1 \
        -padding 0 -sticky nsew -state normal -text {Log settings} -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo38.t1
    spinbox $site_4_1.spi58 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable maxLogSize -to 100.0 \
        -values 1048576 
    vTcl:DefineAlias "$site_4_1.spi58" "maxLogSizeEdit" vTcl:WidgetProc "npSettings" 1
    ttk::label $site_4_1.tLa59 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {Max log size (bytes)} 
    vTcl:DefineAlias "$site_4_1.tLa59" "TLabel6" vTcl:WidgetProc "npSettings" 1
    ttk::label $site_4_1.tLa60 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {Show this events in log:} 
    vTcl:DefineAlias "$site_4_1.tLa60" "TLabel7" vTcl:WidgetProc "npSettings" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_4_1.tCh61 \
        -variable sysStartUp -takefocus {} -text {System startup} 
    vTcl:DefineAlias "$site_4_1.tCh61" "TCheckbutton5" vTcl:WidgetProc "npSettings" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_4_1.tCh62 \
        -variable sysShutdown -takefocus {} -text {System shutdown} 
    vTcl:DefineAlias "$site_4_1.tCh62" "TCheckbutton6" vTcl:WidgetProc "npSettings" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_4_1.tCh63 \
        -variable ip1Log -takefocus {} -text {IP1 avialiblity} 
    vTcl:DefineAlias "$site_4_1.tCh63" "TCheckbutton7" vTcl:WidgetProc "npSettings" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_4_1.tCh64 \
        -variable ip2Log -takefocus {} -text {IP2 avialiblity} 
    vTcl:DefineAlias "$site_4_1.tCh64" "TCheckbutton8" vTcl:WidgetProc "npSettings" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_4_1.tCh65 \
        -variable comPortLog -takefocus {} -text {COM events} 
    vTcl:DefineAlias "$site_4_1.tCh65" "TCheckbutton9" vTcl:WidgetProc "npSettings" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $site_4_1.tCh66 \
        -variable tempLog -takefocus {} -text {Temperature changings} 
    vTcl:DefineAlias "$site_4_1.tCh66" "TCheckbutton10" vTcl:WidgetProc "npSettings" 1
    place $site_4_1.spi58 \
        -in $site_4_1 -x 130 -y 10 -anchor nw -bordermode ignore 
    place $site_4_1.tLa59 \
        -in $site_4_1 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_4_1.tLa60 \
        -in $site_4_1 -x 10 -y 40 -anchor nw -bordermode ignore 
    place $site_4_1.tCh61 \
        -in $site_4_1 -x 10 -y 70 -anchor nw -bordermode ignore 
    place $site_4_1.tCh62 \
        -in $site_4_1 -x 10 -y 100 -anchor nw -bordermode ignore 
    place $site_4_1.tCh63 \
        -in $site_4_1 -x 10 -y 130 -anchor nw -bordermode ignore 
    place $site_4_1.tCh64 \
        -in $site_4_1 -x 10 -y 160 -anchor nw -bordermode ignore 
    place $site_4_1.tCh65 \
        -in $site_4_1 -x 10 -y 190 -anchor nw -bordermode ignore 
    place $site_4_1.tCh66 \
        -in $site_4_1 -x 10 -y 220 -anchor nw -bordermode ignore 
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu42 \
        -takefocus {} -text OK 
    vTcl:DefineAlias "$top.tBu42" "TButton1" vTcl:WidgetProc "npSettings" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu43 \
        -takefocus {} -text Cancel 
    vTcl:DefineAlias "$top.tBu43" "TButton2" vTcl:WidgetProc "npSettings" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo38 \
        -in $top -x 0 -y 0 -width 302 -relwidth 0 -height 306 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu42 \
        -in $top -x 150 -y 310 -anchor nw -bordermode ignore 
    place $top.tBu43 \
        -in $top -x 230 -y 310 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

