#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 11, 2018 05:46:05 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global ip1
    ip1 = StringVar()
    global ip2
    ip2 = StringVar()
    global ip1rebootChecked
    ip1rebootChecked = StringVar()
    global ip2rebootChecked
    ip2rebootChecked = StringVar()
    global comPortEnabledChecked
    comPortEnabledChecked = StringVar()
    global comPort
    comPort = StringVar()
    global enableAutoSpeed
    enableAutoSpeed = StringVar()
    global comSpeed
    comSpeed = StringVar()
    global critTemp
    critTemp = StringVar()
    global maxLogSize
    maxLogSize = StringVar()
    global sysStartUp
    sysStartUp = StringVar()
    global sysShutdown
    sysShutdown = StringVar()
    global ip1Log
    ip1Log = StringVar()
    global ip2Log
    ip2Log = StringVar()
    global comPortLog
    comPortLog = StringVar()
    global tempLog
    tempLog = StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import tk_settingsForm
    tk_settingsForm.vp_start_gui()


