# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/es89/Dropbox/Projects/Python/NetPing_1.3/ui/netPingSettings.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(405, 285)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setSizeGripEnabled(True)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 394, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 391, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.ip1reboot = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.ip1reboot.setObjectName("ip1reboot")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ip1reboot)
        self.ip1Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ip1Edit.setObjectName("ip1Edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ip1Edit)
        self.ip2reboot = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.ip2reboot.setObjectName("ip2reboot")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ip2reboot)
        self.ip2Edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ip2Edit.setObjectName("ip2Edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ip2Edit)
        self.comPortEnabled = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.comPortEnabled.setObjectName("comPortEnabled")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.comPortEnabled)
        self.comEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.comEdit.setObjectName("comEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comEdit)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.maxTempEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.maxTempEdit.setObjectName("maxTempEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.maxTempEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comSpeed = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.comSpeed.setObjectName("comSpeed")
        self.horizontalLayout.addWidget(self.comSpeed)
        self.enableAutoSpeedCheckbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.enableAutoSpeedCheckbox.setObjectName("enableAutoSpeedCheckbox")
        self.horizontalLayout.addWidget(self.enableAutoSpeedCheckbox)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 471, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.sysStartUp = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.sysStartUp.setObjectName("sysStartUp")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sysStartUp)
        self.sysShutdown = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.sysShutdown.setObjectName("sysShutdown")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sysShutdown)
        self.ip1Log = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.ip1Log.setObjectName("ip1Log")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ip1Log)
        self.ip2Log = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.ip2Log.setObjectName("ip2Log")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ip2Log)
        self.comPortLog = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.comPortLog.setObjectName("comPortLog")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.comPortLog)
        self.tempLog = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.tempLog.setObjectName("tempLog")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tempLog)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.maxLogSize = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.maxLogSize.setMaximumSize(QtCore.QSize(150, 16777215))
        self.maxLogSize.setMaximum(1048576000)
        self.maxLogSize.setProperty("value", 1048576)
        self.maxLogSize.setObjectName("maxLogSize")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.maxLogSize)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem1 = QtWidgets.QSpacerItem(131, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.okButton = QtWidgets.QPushButton(self.layoutWidget)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.layoutWidget.raise_()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.okButton.clicked.connect(Dialog.accept)
        self.cancelButton.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки"))
        self.ip1reboot.setText(_translate("Dialog", "Перезагружать при недоступности IP1"))
        self.ip2reboot.setText(_translate("Dialog", "Перезагружать при недоступности IP2"))
        self.comPortEnabled.setText(_translate("Dialog", "Контролировать COM-порт?"))
        self.label_4.setText(_translate("Dialog", "Критическая температура"))
        self.comSpeed.setText(_translate("Dialog", "COM-speed"))
        self.enableAutoSpeedCheckbox.setText(_translate("Dialog", "auto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Общие"))
        self.label_5.setText(_translate("Dialog", "События, отображаемые в логе:"))
        self.sysStartUp.setText(_translate("Dialog", "Запуск системы"))
        self.sysShutdown.setText(_translate("Dialog", "Выключение"))
        self.ip1Log.setText(_translate("Dialog", "Доступность IP1"))
        self.ip2Log.setText(_translate("Dialog", "Доступность IP2"))
        self.comPortLog.setText(_translate("Dialog", "Доступность COM"))
        self.tempLog.setText(_translate("Dialog", "Изменение температуры"))
        self.label.setText(_translate("Dialog", "Максим. размер лога (в байтах)  "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Настройки лога"))
        self.okButton.setText(_translate("Dialog", "&OK"))
        self.cancelButton.setText(_translate("Dialog", "&Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

